name: kenya-agri
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - xgboost
  - lightgbm
  - statsmodels
  - geopandas
  - folium
  - shapely
  - nltk
  - spacy
  - gensim
  - joblib
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab

  - pip:
    - requests
    - beautifulsoup4
    - lxml
    - tqdm
    - pdfplumber
    - prophet
    - vaderSentiment
    - transformers
    - torch
    - bertopic
    - sentence-transformers
    - shap
    - streamlit
    - openpyxl
